apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-dashboard
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: streamlit-dashboard:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
    nodePort: 30010
  type: NodePort
